### ISSUE TITLE
Dual-licensing?

### ISSUE THREAD

**Issue by seanchas116** [johnboiles/coremediaio-dal-minimal-example#7]
First of all, thank you for the project! It helps me understanding what should be done in DAL virtual camera plugins very much.
I wrote [a Swift version of minimal DAL plugin example](https://github.com/seanchas116/SimpleDALPlugin). I would like to release it under the MIT license but it is based on coremediaio-dal-minimal-example which is GPL licensed.

Is it possible to dual-license coremediaio-dal-minimal-example (GPL + a permissive license such as MIT)?
I think coremediaio-dal-minimal-example is the best starting point to create DAL plugins so reducing license restructions would be super helpful.

**Comment by johnboiles** [comment]
@seanchas116 this is awesome! I was very tempted to write this in Swift, but my goal is to use this to contribute to OBS and the OBS lead dev [asked](https://github.com/obsproject/rfcs/pull/15#issuecomment-611859159) to keep it in Objective-C so as not to introduce another language into that codebase. Thanks for providing a Swift implementation!

If I did a dual license, the MIT license would supersede the GPL license right (since it's more permissive)?

I mostly picked GPLv2 since that's what OBS uses. But I also like the idea of requiring people who use this to contribute back to the effort -- when I was implementing this It felt like I was fumbling around in the dark since there are very few open source CoreMediaIO DAL examples out there (I only found Apple's Sample code and and webcamoid.

But given as this would probably be incorporated into another program (and not used as-is) I suppose GPLv2 would only make this useful for other GPL'd software.

All that to say, I'll go with MIT :) And maybe I'll add an impassioned plea into the README.md for people to please contribute back if they find ways this could be better / simpler / or more flexible.

**Comment by johnboiles** [comment]
Changed the license to MIT in af42e8f4a33.

**Comment by seanchas116** [comment]
Thank you for changing license to MIT! In [SimpleDALPlugin](https://github.com/seanchas116/SimpleDALPlugin/tree/master/SimpleDALPlugin) I have made some changes which may fix problems so I'll contribute back to coremediaio-dal-minimal-example.
